### ISSUE TITLE
separate out deployment and tests

### ISSUE THREAD

**Issue by skchoi56** [rbraju/cribl-tests#1]
Hi Rajesh, is it possible to separate out the app deployment with the test cases?

Also how would you know when to start the tests (besides the sleep you have there currently) -- is there anything that indicates when event processing is done?

**Comment by rbraju** [comment]
@skchoi56 I can separate this into two repos. One for app (cribl-app) and another one for tests (cribl-test). 
Once we build and package the app, we can run tests against it and then promote to release (push to dockerhub) if the tests run successfully. Would that be fine?

Also regarding when to run the tests, I think we can wait until agent and splitter completes their task before validating the contents in target.

**Comment by rbraju** [comment]
@skchoi56 
Separated out app deployment and test case development. Created two repos and tracking them separately. Also created jobs for both app and tests in Jenkins. For changes in app, the job will build the app and run the tests. For changes in test, the job will pick the latest artifact and run the tests. Have updated README.md in both the repos.

**Comment by skchoi56** [comment]
Thanks @rbraju ! 
I noticed in the README, under enhancements, you note: `Currently input file is placed under the agent directory. Need to enhance the tests to run with a different set of files.`

Not necessary to add the data now, but please consider how you'd add tests with different input files -- would this require re-building the app? Can multiple input files be tested with only building the app once* and running various tests?

**Comment by rbraju** [comment]
@skchoi56 
Thanks for the response.

I thought about testing with multiple input files but the file is closely tied with the agent (within the repository). Not sure if we can test it without rebuilding the app since the filename is hardcoded in `input.json`. I can pass different inputs from the tests if the app is able to take it as an input. 

Another way is to package target, splitter and agent as separate components and build the agent alone after modifying `inputs.json`. Couldn't think of a better way to test without modifying the app but still trying.

**Comment by skchoi56** [comment]
lets discuss during meet the team :)
